#[path = r#"../algorithm/tgt_refcount.rs"#]
pub mod algorithm_tgt_refcount;
#[path = r#"../algorithm/tgt_unsafe.rs"#]
pub mod algorithm_tgt_unsafe;
#[path = r#"../arpa_inet/tgt_refcount.rs"#]
pub mod arpa_inet_tgt_refcount;
#[path = r#"../arpa_inet/tgt_unsafe.rs"#]
pub mod arpa_inet_tgt_unsafe;
#[path = r#"../array/tgt_refcount.rs"#]
pub mod array_tgt_refcount;
#[path = r#"../array/tgt_unsafe.rs"#]
pub mod array_tgt_unsafe;
#[path = r#"../assert/tgt_refcount.rs"#]
pub mod assert_tgt_refcount;
#[path = r#"../assert/tgt_unsafe.rs"#]
pub mod assert_tgt_unsafe;
#[path = r#"../brotli/tgt_refcount.rs"#]
pub mod brotli_tgt_refcount;
#[path = r#"../brotli/tgt_unsafe.rs"#]
pub mod brotli_tgt_unsafe;
#[path = r#"../builtin/tgt_refcount.rs"#]
pub mod builtin_tgt_refcount;
#[path = r#"../builtin/tgt_unsafe.rs"#]
pub mod builtin_tgt_unsafe;
#[path = r#"../carray/tgt_refcount.rs"#]
pub mod carray_tgt_refcount;
#[path = r#"../carray/tgt_unsafe.rs"#]
pub mod carray_tgt_unsafe;
#[path = r#"../cmath/tgt_unsafe.rs"#]
pub mod cmath_tgt_unsafe;
#[path = r#"../cstdlib/tgt_refcount.rs"#]
pub mod cstdlib_tgt_refcount;
#[path = r#"../cstdlib/tgt_unsafe.rs"#]
pub mod cstdlib_tgt_unsafe;
#[path = r#"../cstring/tgt_refcount.rs"#]
pub mod cstring_tgt_refcount;
#[path = r#"../cstring/tgt_unsafe.rs"#]
pub mod cstring_tgt_unsafe;
#[path = r#"../deque/tgt_refcount.rs"#]
pub mod deque_tgt_refcount;
#[path = r#"../deque/tgt_unsafe.rs"#]
pub mod deque_tgt_unsafe;
#[path = r#"../dirent/tgt_refcount.rs"#]
pub mod dirent_tgt_refcount;
#[path = r#"../dirent/tgt_unsafe.rs"#]
pub mod dirent_tgt_unsafe;
#[path = r#"../errno/tgt_refcount.rs"#]
pub mod errno_tgt_refcount;
#[path = r#"../errno/tgt_unsafe.rs"#]
pub mod errno_tgt_unsafe;
#[path = r#"../eventfd/tgt_unsafe.rs"#]
pub mod eventfd_tgt_unsafe;
#[path = r#"../fcntl/tgt_refcount.rs"#]
pub mod fcntl_tgt_refcount;
#[path = r#"../fcntl/tgt_unsafe.rs"#]
pub mod fcntl_tgt_unsafe;
#[path = r#"../fnmatch/tgt_unsafe.rs"#]
pub mod fnmatch_tgt_unsafe;
#[path = r#"../fstream/tgt_refcount.rs"#]
pub mod fstream_tgt_refcount;
#[path = r#"../fstream/tgt_unsafe.rs"#]
pub mod fstream_tgt_unsafe;
#[path = r#"../functional/tgt_refcount.rs"#]
pub mod functional_tgt_refcount;
#[path = r#"../functional/tgt_unsafe.rs"#]
pub mod functional_tgt_unsafe;
#[path = r#"../ifaddrs/tgt_refcount.rs"#]
pub mod ifaddrs_tgt_refcount;
#[path = r#"../ifaddrs/tgt_unsafe.rs"#]
pub mod ifaddrs_tgt_unsafe;
#[path = r#"../initializer_list/tgt_unsafe.rs"#]
pub mod initializer_list_tgt_unsafe;
#[path = r#"../ioctl/tgt_refcount.rs"#]
pub mod ioctl_tgt_refcount;
#[path = r#"../ioctl/tgt_unsafe.rs"#]
pub mod ioctl_tgt_unsafe;
#[path = r#"../iomanip/tgt_unsafe.rs"#]
pub mod iomanip_tgt_unsafe;
#[path = r#"../iostream/tgt_refcount.rs"#]
pub mod iostream_tgt_refcount;
#[path = r#"../iostream/tgt_unsafe.rs"#]
pub mod iostream_tgt_unsafe;
#[path = r#"../ip/tgt_refcount.rs"#]
pub mod ip_tgt_refcount;
#[path = r#"../ip/tgt_unsafe.rs"#]
pub mod ip_tgt_unsafe;
#[path = r#"../limits/tgt_unsafe.rs"#]
pub mod limits_tgt_unsafe;
#[path = r#"../locale/tgt_refcount.rs"#]
pub mod locale_tgt_refcount;
#[path = r#"../locale/tgt_unsafe.rs"#]
pub mod locale_tgt_unsafe;
#[path = r#"../map/tgt_refcount.rs"#]
pub mod map_tgt_refcount;
#[path = r#"../map/tgt_unsafe.rs"#]
pub mod map_tgt_unsafe;
#[path = r#"../math/tgt_unsafe.rs"#]
pub mod math_tgt_unsafe;
#[path = r#"../net_if/tgt_refcount.rs"#]
pub mod net_if_tgt_refcount;
#[path = r#"../net_if/tgt_unsafe.rs"#]
pub mod net_if_tgt_unsafe;
#[path = r#"../netdb/tgt_refcount.rs"#]
pub mod netdb_tgt_refcount;
#[path = r#"../netdb/tgt_unsafe.rs"#]
pub mod netdb_tgt_unsafe;
#[path = r#"../pair/tgt_refcount.rs"#]
pub mod pair_tgt_refcount;
#[path = r#"../pair/tgt_unsafe.rs"#]
pub mod pair_tgt_unsafe;
#[path = r#"../poll/tgt_refcount.rs"#]
pub mod poll_tgt_refcount;
#[path = r#"../poll/tgt_unsafe.rs"#]
pub mod poll_tgt_unsafe;
#[path = r#"../pwd/tgt_refcount.rs"#]
pub mod pwd_tgt_refcount;
#[path = r#"../pwd/tgt_unsafe.rs"#]
pub mod pwd_tgt_unsafe;
#[path = r#"../rustls/tgt_unsafe.rs"#]
pub mod rustls_tgt_unsafe;
#[path = r#"../select/tgt_refcount.rs"#]
pub mod select_tgt_refcount;
#[path = r#"../select/tgt_unsafe.rs"#]
pub mod select_tgt_unsafe;
#[path = r#"../signal/tgt_unsafe.rs"#]
pub mod signal_tgt_unsafe;
#[path = r#"../socket/tgt_refcount.rs"#]
pub mod socket_tgt_refcount;
#[path = r#"../socket/tgt_unsafe.rs"#]
pub mod socket_tgt_unsafe;
#[path = r#"../stat/tgt_refcount.rs"#]
pub mod stat_tgt_refcount;
#[path = r#"../stat/tgt_unsafe.rs"#]
pub mod stat_tgt_unsafe;
#[path = r#"../stdio/tgt_refcount.rs"#]
pub mod stdio_tgt_refcount;
#[path = r#"../stdio/tgt_unsafe.rs"#]
pub mod stdio_tgt_unsafe;
#[path = r#"../string/tgt_refcount.rs"#]
pub mod string_tgt_refcount;
#[path = r#"../string/tgt_unsafe.rs"#]
pub mod string_tgt_unsafe;
#[path = r#"../termios/tgt_refcount.rs"#]
pub mod termios_tgt_refcount;
#[path = r#"../termios/tgt_unsafe.rs"#]
pub mod termios_tgt_unsafe;
#[path = r#"../time/tgt_refcount.rs"#]
pub mod time_tgt_refcount;
#[path = r#"../time/tgt_unsafe.rs"#]
pub mod time_tgt_unsafe;
#[path = r#"../unique_ptr/tgt_refcount.rs"#]
pub mod unique_ptr_tgt_refcount;
#[path = r#"../unique_ptr/tgt_unsafe.rs"#]
pub mod unique_ptr_tgt_unsafe;
#[path = r#"../unistd/tgt_refcount.rs"#]
pub mod unistd_tgt_refcount;
#[path = r#"../unistd/tgt_unsafe.rs"#]
pub mod unistd_tgt_unsafe;
#[path = r#"../vector/tgt_refcount.rs"#]
pub mod vector_tgt_refcount;
#[path = r#"../vector/tgt_unsafe.rs"#]
pub mod vector_tgt_unsafe;
#[path = r#"../xattr/tgt_unsafe.rs"#]
pub mod xattr_tgt_unsafe;
