function(generate_buildconfig_py outdir)
  file(CONFIGURE
    OUTPUT "${outdir}/_buildconfig.py"
    CONTENT [[
"""Generated by CMake, do not edit."""

from pathlib import Path

CXX = Path(r"@CMAKE_CXX_COMPILER@")
CC = Path(r"@CMAKE_C_COMPILER@")
]]
    ESCAPE_QUOTES
    @ONLY
  )
endfunction()
