// Copyright (c) 2022-present INESC-ID.
// Distributed under the MIT license that can be found in the LICENSE file.

#include <errno.h>

int *f1(void) { return cpp2rust_errno(); }

int f2(void) { return E2BIG; }
int f3(void) { return EACCES; }
int f4(void) { return EADDRINUSE; }
int f5(void) { return EADDRNOTAVAIL; }
int f6(void) { return EAFNOSUPPORT; }
int f7(void) { return EAGAIN; }
int f8(void) { return EALREADY; }
int f9(void) { return EBADF; }
int f10(void) { return EBADMSG; }
int f11(void) { return EBUSY; }
int f12(void) { return ECANCELED; }
int f13(void) { return ECHILD; }
int f14(void) { return ECONNABORTED; }
int f15(void) { return ECONNREFUSED; }
int f16(void) { return ECONNRESET; }
int f17(void) { return EDEADLK; }
int f18(void) { return EDESTADDRREQ; }
int f19(void) { return EDOM; }
int f20(void) { return EDQUOT; }
int f21(void) { return EEXIST; }
int f22(void) { return EFAULT; }
int f23(void) { return EFBIG; }
int f24(void) { return EHOSTDOWN; }
int f25(void) { return EHOSTUNREACH; }
int f26(void) { return EIDRM; }
int f27(void) { return EILSEQ; }
int f28(void) { return EINPROGRESS; }
int f29(void) { return EINTR; }
int f30(void) { return EINVAL; }
int f31(void) { return EIO; }
int f32(void) { return EISCONN; }
int f33(void) { return EISDIR; }
int f34(void) { return ELOOP; }
int f35(void) { return EMFILE; }
int f36(void) { return EMLINK; }
int f37(void) { return EMSGSIZE; }
int f38(void) { return EMULTIHOP; }
int f39(void) { return ENAMETOOLONG; }
int f40(void) { return ENETDOWN; }
int f41(void) { return ENETRESET; }
int f42(void) { return ENETUNREACH; }
int f43(void) { return ENFILE; }
int f44(void) { return ENOBUFS; }
int f45(void) { return ENODATA; }
int f46(void) { return ENODEV; }
int f47(void) { return ENOENT; }
int f48(void) { return ENOEXEC; }
int f49(void) { return ENOLCK; }
int f50(void) { return ENOLINK; }
int f51(void) { return ENOMEM; }
int f52(void) { return ENOMSG; }
int f53(void) { return ENOPROTOOPT; }
int f54(void) { return ENOSPC; }
int f55(void) { return ENOSR; }
int f56(void) { return ENOSTR; }
int f57(void) { return ENOSYS; }
int f58(void) { return ENOTCONN; }
int f59(void) { return ENOTDIR; }
int f60(void) { return ENOTEMPTY; }
int f61(void) { return ENOTRECOVERABLE; }
int f62(void) { return ENOTSOCK; }
int f63(void) { return ENOTSUP; }
int f64(void) { return ENOTBLK; }
int f65(void) { return ENOTTY; }
int f66(void) { return ENXIO; }
int f67(void) { return EOPNOTSUPP; }
int f68(void) { return EOVERFLOW; }
int f69(void) { return EOWNERDEAD; }
int f70(void) { return EPERM; }
int f71(void) { return EPFNOSUPPORT; }
int f72(void) { return EPIPE; }
int f73(void) { return EPROTO; }
int f74(void) { return EPROTONOSUPPORT; }
int f75(void) { return EPROTOTYPE; }
int f76(void) { return ERANGE; }
int f77(void) { return EREMOTE; }
int f78(void) { return EROFS; }
int f79(void) { return ESHUTDOWN; }
int f80(void) { return ESOCKTNOSUPPORT; }
int f81(void) { return ESPIPE; }
int f82(void) { return ESRCH; }
int f83(void) { return ESTALE; }
int f84(void) { return ETIME; }
int f85(void) { return ETIMEDOUT; }
int f86(void) { return ETOOMANYREFS; }
int f87(void) { return ETXTBSY; }
int f88(void) { return EUSERS; }
int f89(void) { return EWOULDBLOCK; }
int f90(void) { return EXDEV; }

#if defined(__linux__)
int f91(void) { return EADV; }
int f92(void) { return EBADE; }
int f93(void) { return EBADFD; }
int f94(void) { return EBADR; }
int f95(void) { return EBADRQC; }
int f96(void) { return EBADSLT; }
int f97(void) { return EBFONT; }
int f98(void) { return ECHRNG; }
int f99(void) { return ECOMM; }
int f100(void) { return EDEADLOCK; }
int f101(void) { return EDOTDOT; }
int f102(void) { return EHWPOISON; }
int f103(void) { return EISNAM; }
int f104(void) { return EKEYEXPIRED; }
int f105(void) { return EKEYREJECTED; }
int f106(void) { return EKEYREVOKED; }
int f107(void) { return EL2HLT; }
int f108(void) { return EL2NSYNC; }
int f109(void) { return EL3HLT; }
int f110(void) { return EL3RST; }
int f111(void) { return ELIBACC; }
int f112(void) { return ELIBBAD; }
int f113(void) { return ELIBEXEC; }
int f114(void) { return ELIBMAX; }
int f115(void) { return ELIBSCN; }
int f116(void) { return ELNRNG; }
int f117(void) { return EMEDIUMTYPE; }
int f118(void) { return ENAVAIL; }
int f119(void) { return ENOANO; }
int f120(void) { return ENOCSI; }
int f121(void) { return ENOKEY; }
int f122(void) { return ENOMEDIUM; }
int f123(void) { return ENONET; }
int f124(void) { return ENOPKG; }
int f125(void) { return ENOTNAM; }
int f126(void) { return ENOTUNIQ; }
int f127(void) { return EREMCHG; }
int f128(void) { return EREMOTEIO; }
int f129(void) { return ERESTART; }
int f130(void) { return ERFKILL; }
int f131(void) { return ESRMNT; }
int f132(void) { return ESTRPIPE; }
int f133(void) { return EUCLEAN; }
int f134(void) { return EUNATCH; }
int f135(void) { return EXFULL; }
#elif defined(__APPLE__)
int f136(void) { return EAUTH; }
int f137(void) { return EBADARCH; }
int f138(void) { return EBADEXEC; }
int f139(void) { return EBADMACHO; }
int f140(void) { return EBADRPC; }
int f141(void) { return EDEVERR; }
int f142(void) { return EFTYPE; }
int f143(void) { return ENEEDAUTH; }
int f144(void) { return ENOATTR; }
int f145(void) { return ENOPOLICY; }
int f146(void) { return EPROCLIM; }
int f147(void) { return EPROCUNAVAIL; }
int f148(void) { return EPROGMISMATCH; }
int f149(void) { return EPROGUNAVAIL; }
int f150(void) { return EPWROFF; }
int f151(void) { return EQFULL; }
int f152(void) { return ERPCMISMATCH; }
int f153(void) { return ESHLIBVERS; }
#endif
