name: Format Check

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - name: Setup Python
        run: pip install ruff

      - name: Configure
        run: cmake -GNinja -B build -S .

      - name: Format files
        run: ninja format
        working-directory: build

      - name: Check format
        run: git diff --exit-code
