name: "Run tests"

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: ubuntu-libstdcxx, os: ubuntu-latest }
          - { name: ubuntu-libcxx, os: ubuntu-latest, stdlib: libc++ }
          - { name: macos, os: macos-latest }
        build_type: [Debug, Release]

    runs-on: ${{ matrix.config.os }}
    name: Run Tests (${{ matrix.config.name }}, ${{ matrix.build_type }})

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 23

      - name: Install libc++
        if: matrix.config.stdlib == 'libc++'
        run: |
          sudo apt-get install -y libc++-23-dev libc++abi-23-dev
          echo "CPP2RUST_STDLIB=libc++" >> "$GITHUB_ENV"

      - name: Configure
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DLIT_FLAGS="-v" \
                -GNinja ..

      - name: Build
        run: ninja
        working-directory: build

      - name: Run unit tests
        run: ninja check
        working-directory: build
